spring.application.name=flatbnb

#spring.jpa.show-sql=true
#spring.jpa.open-in-view=true
#spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=elMejorSecretoJamasGuardadoNadieLoSabraNuncaJamas
jwt.duration=10
jwt.refresh.duration=3
activation.duration=30

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true

sendgrid.api.key={SENDGRID_API_KEY}
resend.api.key=${RESEND_API_KEY}

spring.profiles.active=dev,pgsql
spring.datasource.url=jdbc:postgresql://localhost:5432/tu_db?charSet=UTF8